ProyectSoftware/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf.urls import url


    
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^proveedor/', include('apps.Proveedor.urls')),
	url(r'^producto/', include('apps.Producto.urls')),
	url(r'^plato/', include('apps.Plato.urls')),
    url(r'^empleado/', include('apps.Empleado.urls')),
    url(r'^usuario/', include('apps.Usuario.urls', namespace='usuario')),
    url(r'^inventario/', include('apps.Inventario.urls', namespace='inventario')),
    url(r'^registroventa/', include('apps.Registroventa.urls', namespace='registroventa')),
    url(r'^inventariopro/', include('apps.Inventarioproducto.urls', namespace='inventarioproducto')),
    url(r'^accounts/login/', login, {'template_name':'index.html'},name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),   



]

apps/Inventarioproducto/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.Inventarioproducto.views import Inventariopinicio, InventariopList, InventariopCreate, InventariopUpdate, InventariopDelete, product_list
urlpatterns = [
    url(r'^index$',Inventariopinicio , name='inventariop_inicio'),
    url(r'^search$', product_list, name='inventario_search'),
 	url(r'^nuevo$',login_required(InventariopCreate.as_view()) , name='inventariop_crear'),
 	url(r'^listar$', login_required(InventariopList.as_view()), name='inventariop_listar'),
 	url(r'^editar/(?P<pk>\d+)/$', login_required(InventariopUpdate.as_view()), name='inventariop_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(InventariopDelete.as_view()), name='inventariop_eliminar'),
         
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	{% block extrahead %}
	{% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

	<title>{% block title %} Document {% endblock %}</title>
</head>
<body>
<div class="container">

{% block navbar %}
    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                 <nav class="navbar navbar-default">
                     <div class="container-fluid">
                        <div class="navbar-header">
                          <a class="navbar-brand" href="#">Home</a>
                        </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                         <ul class="nav navbar-nav">
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Empleados<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                               <li><a href="{% url 'empleado_listar' %}">Gestionar Empleado</a></li>
                               <li><a href="{% url 'empleado_crear' %}">Agregar Empleado</a></li>
                              </ul>
                            </li>
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Platos <span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                               <li><a href="{% url 'plato_listar' %}">Gestionar PLato</a></li>
                               <li><a href="{% url 'plato_crear' %}">Agregar PLato</a></li>
                              </ul>
                            </li>
                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Productos<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                 <li><a href="{% url 'producto_listar' %}">Gestionar Producto</a></li>
                                 <li><a href="{% url 'producto_crear' %}">Agregar Producto</a></li>
                              </ul>
                             </li>
                              <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Proveedores <span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                               <li><a href="{% url 'proveedor_listar' %}">Gestionar Proveedores</a></li>
                               <li><a href="{% url 'proveedor_crear' %}">Agregar Proveedores</a></li>
                              </ul>
                            </li>
                         </ul>

                         <ul class="nav navbar-nav navbar-right">
                              <div class="navbar-header">
                                <li><a class="navbar-brand" href="{% url 'inventarioproducto:inventario_search'%}">Informe inventario</a></li>
                              </div>
                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Opciones<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                 <li><a href="{% url 'logout' %}">Salir</a></li>
                              </ul>
                              
                            </li>
                            
                         </ul>
                        </div>
                    </div>
                </nav>
            </div>
              </div>
          </div>
      </div>

   {% endblock %}﻿


	{% block content %}
	<h5>bloque de contenido</h5>
	{% endblock %}

	{% block footer %}
	{% endblock %}
</div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block extrajs %}
	{% endblock %}

</body>
</html>

templates/base/header.html
<header>hola</header>