ProyectSoftware/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf.urls import url


    
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^proveedor/', include('apps.Proveedor.urls')),
	url(r'^producto/', include('apps.Producto.urls')),
	url(r'^plato/', include('apps.Plato.urls')),
    url(r'^empleado/', include('apps.Empleado.urls')),
    url(r'^usuario/', include('apps.Usuario.urls', namespace='usuario')),
    url(r'^inventario/', include('apps.Inventario.urls', namespace='inventario')),
    url(r'^registroventa/', include('apps.Registroventa.urls', namespace='registroventa')),
    url(r'^inventariopro/', include('apps.Inventarioproducto.urls', namespace='inventarioproducto')),
    url(r'^accounts/login/', login, {'template_name':'index.html'},name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),   



]

apps/Inventario/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.Inventario.views import Inventarioinicio, InventarioList, InventarioCreate, InventarioUpdate, InventarioDelete
urlpatterns = [
    url(r'^index$',Inventarioinicio , name='inventario_inicio'),
 	url(r'^nuevo$',login_required(InventarioCreate.as_view()) , name='inventario_crear'),
 	url(r'^listar$', login_required(InventarioList.as_view()), name='inventario_listar'),
 	url(r'^editar/(?P<pk>\d+)/$', login_required(InventarioUpdate.as_view()), name='inventario_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(InventarioDelete.as_view()), name='inventario_eliminar'),
         
]

apps/Inventarioproducto/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.Inventarioproducto.views import Inventariopinicio, InventariopList, InventariopCreate, InventariopUpdate, InventariopDelete, product_list
urlpatterns = [
    url(r'^index$',Inventariopinicio , name='inventariop_inicio'),
    url(r'^search$', product_list, name='inventario_search'),
 	url(r'^nuevo$',login_required(InventariopCreate.as_view()) , name='inventariop_crear'),
 	url(r'^listar$', login_required(InventariopList.as_view()), name='inventariop_listar'),
 	url(r'^editar/(?P<pk>\d+)/$', login_required(InventariopUpdate.as_view()), name='inventariop_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(InventariopDelete.as_view()), name='inventariop_eliminar'),
         
]

apps/Inventarioproducto/models.py
from django.db import models
from apps.Producto.models import Producto
from apps.Inventario.models import Inventario


# Create your models here.
class Inventarioproducto(models.Model):
	inventario = models.ForeignKey(Inventario, null=True,blank=True,on_delete=models.CASCADE)
	producto = models.ForeignKey(Producto, null=True,blank=True,on_delete=models.CASCADE)
	cantidad = models.IntegerField()
	
	

apps/Inventarioproducto/forms.py
from django import forms
from apps.Inventarioproducto.models import Inventarioproducto

class InventariopForm(forms.ModelForm):

	class Meta:
		model = Inventarioproducto

		fields = [
			'inventario',
			'producto',
			'cantidad',
		]
		labels = {
			'inventario' : 'Inventario',
			'producto': 'Nombre producto',
			'cantidad' : 'Cantidad',
		}
		widgets = {
			'inventario': forms.Select(attrs={'class':'form-control'}),
			'producto' : forms.Select(attrs={'class':'form-control'}),
			'cantidad' : forms.TextInput(attrs={'class':'form-control'}),
		}

apps/Inventarioproducto/views.py
from django.shortcuts import render ,redirect
from django.http import HttpResponse
from apps.Inventarioproducto.filters import ProductFilter
from apps.Inventarioproducto.forms import InventariopForm
from apps.Inventarioproducto.models import Inventarioproducto
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

def Inventariopinicio(request):
	#titulo = "Bienvenidos"
	if request.user.is_authenticated():
		titulo = "hola, %s!" %(request.user)
	form = InventariopForm (request.POST)

	context ={
		"titulo":titulo,
		"form":form
	}
	if form.is_valid():
			instance = form.save(commit=False)
			producto = form.cleaned_data.get("producto")
			inventario = form.cleaned_data.get("inventario")	
			cantidad = form.cleaned_data.get("cantidad")	
			form.save()
			
			context ={
			"titulo":"producto %s,cantidad %s quedo reguistrado correctamente. en el inventario %s" %(producto,cantidad,inventario)

	}
	return render(request, 'inventarioproducto/index.html', context)

def product_list(request):
    f = ProductFilter(request.GET, queryset=Inventarioproducto.objects.all())
    return render(request, 'inventarioproducto/index.html', {'filter': f})

class InventariopList(ListView):
	model = Inventarioproducto
	template_name = 'inventarioproducto/inventariop_list.html'

class InventariopCreate(CreateView):
	model = Inventarioproducto
	form_class = InventariopForm
	template_name = 'inventarioproducto/inventariop_form.html'
	success_url = reverse_lazy('inventarioproducto:inventariop_crear')

class InventariopUpdate(UpdateView):
	model = Inventarioproducto
	form_class = InventariopForm
	template_name = 'inventarioproducto/inventariop_form.html'
	success_url = reverse_lazy('plato_listar')

class InventariopDelete(DeleteView):
	model = Inventarioproducto
	form_class = InventariopForm
	template_name = 'inventarioproducto/inventariop_delete.html'
	success_url = reverse_lazy('plato_listar')

templates/inventarioproducto/index.html
{% extends 'base/base.html' %}

{% block content %}
<form method="get">
   		{{ filter.form.as_p }}
   		<button type="submit">Search</button>
</form>
<ul>
	{% for obj in filter.qs %}
  		<li>{{ obj.inventario.fecha }} - {{ obj.producto }} - {{ obj.cantidad }}</li>
	{% endfor %}
</ul>
{% endblock %}

templates/inventarioproducto/inventariop_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.id }},{{ object.descripcion }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'inventario:inventario_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/inventarioproducto/inventariop_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method="POST" >
	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit" >Registrar</button>
	
</form>

	

{% endblock %}

templates/inventarioproducto/inventariop_list.html
{% extends 'base/base.html' %}


{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>inventario</td>
			<td>producto</td>
			<td>cantidad</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		
		{% for inventarioproducto in object_list %}	
        <tr>
        	<td>{{ inventarioproducto.id }}</td>
			<td>{{ inventarioproducto.inventario}}</td>
			<td>{{ inventarioproducto.producto }}</td>
			<td>{{ inventarioproducto.cantidad }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'inventarioproducto:inventariop_editar' inventarioproducto.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'inventarioproducto:inventariop_eliminar' inventarioproducto.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% else %}
		<h1>No hay registros de inventarios </h1>
		{% endif %}
	</tbody>
</table> 

{% endblock%}