ProyectSoftware/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf.urls import url


    
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^proveedor/', include('apps.Proveedor.urls')),
	url(r'^producto/', include('apps.Producto.urls')),
	url(r'^plato/', include('apps.Plato.urls')),
    url(r'^empleado/', include('apps.Empleado.urls')),
    url(r'^usuario/', include('apps.Usuario.urls', namespace='usuario')),
    url(r'^inventario/', include('apps.Inventario.urls', namespace='inventario')),
    url(r'^registroventa/', include('apps.Registroventa.urls', namespace='registroventa')),
    url(r'^inventariopro/', include('apps.Inventarioproducto.urls', namespace='inventarioproducto')),
    url(r'^accounts/login/', login, {'template_name':'index.html'},name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),   



]

apps/Usuario/urls.py
from django.conf.urls import url, include
from apps.Usuario.views import RegistroUsuario

urlpatterns = [
url(r'^registrar', RegistroUsuario.as_view(), name="registrar"),
	

]

templates/index.html
{% extends 'base/base.html' %}

{% block title %}
PRODUCTOS DEL PACIFICO
{% endblock %}
{% block navbar%}
{% endblock %}
{% block content %}
<form method="post">
	{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Nombre de usuario:</label>
        		<input class="form-control" type="text" name="username">
    	   </div>
        </div>
    </div>    
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Contraseña:</label>
        		<input class="form-control" type="password" name="password">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
                <a href="{% url 'password_reset' %}">Olvidé mi contraseña</a>
        		<input class="btn btn-primary" type="submit" value="Ingresar">
                <a class="btn btn-primary" href="{% url 'usuario:registrar' %}">Registrar</a>
    	   </div>
        </div>
    </div>
</form>


{% endblock %}