ProyectSoftware/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf.urls import url


    
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^proveedor/', include('apps.Proveedor.urls')),
	url(r'^producto/', include('apps.Producto.urls')),
	url(r'^plato/', include('apps.Plato.urls')),
    url(r'^empleado/', include('apps.Empleado.urls')),
    url(r'^usuario/', include('apps.Usuario.urls', namespace='usuario')),
    url(r'^inventario/', include('apps.Inventario.urls', namespace='inventario')),
    url(r'^registroventa/', include('apps.Registroventa.urls', namespace='registroventa')),
    url(r'^inventariopro/', include('apps.Inventarioproducto.urls', namespace='inventarioproducto')),
    url(r'^accounts/login/', login, {'template_name':'index.html'},name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),   



]

apps/Inventario/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.Inventario.views import Inventarioinicio, InventarioList, InventarioCreate, InventarioUpdate, InventarioDelete
urlpatterns = [
    url(r'^index$',Inventarioinicio , name='inventario_inicio'),
 	url(r'^nuevo$',login_required(InventarioCreate.as_view()) , name='inventario_crear'),
 	url(r'^listar$', login_required(InventarioList.as_view()), name='inventario_listar'),
 	url(r'^editar/(?P<pk>\d+)/$', login_required(InventarioUpdate.as_view()), name='inventario_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(InventarioDelete.as_view()), name='inventario_eliminar'),
         
]

apps/Inventario/models.py
from django.db import models

# Create your models here.
class Inventario(models.Model):
	fecha=models.DateField()
	descripcion = models.CharField(max_length=50)
	
	def __str__(self):
		return '%s - %s - %s' %(self.id,self.descripcion,self.fecha)

apps/Inventario/forms.py
from django import forms
from apps.Inventario.models import Inventario

class InventarioForm(forms.ModelForm):

	class Meta:
		model = Inventario

		fields = [
			'fecha',
			'descripcion',
		]
		labels = {
			'fecha': 'Fecha',
			'descripcion' : 'Descripcion',
		}
		widgets = {
			'fecha':  forms.TextInput(attrs={'class':'form-control'}),
			'descripcion' : forms.TextInput(attrs={'class':'form-control'}),
		}

apps/Inventario/views.py
from django.shortcuts import render ,redirect
from django.http import HttpResponse
from apps.Inventario.forms import InventarioForm
from apps.Inventario.models import Inventario
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

def Inventarioinicio(request):
	#titulo = "Bienvenidos"
	if request.user.is_authenticated():
		titulo = "hola, %s!" %(request.user)
	form = InventarioForm (request.POST)

	context ={
		"titulo":titulo,
		"form":form
	}
	if form.is_valid():
			instance = form.save(commit=False)
			fecha = form.cleaned_data.get("fecha")
			descripcion = form.cleaned_data.get("descripcion")	
			form.save()
			
			context ={
			"titulo":"descripcion %s, quedo reguistrado correctamente. fecha %s" %(descripcion,fecha)

	}
	return render(request, 'inventario/index.html', context)
	
class InventarioList(ListView):
	model = Inventario
	template_name = 'inventario/inventario_list.html'

class InventarioCreate(CreateView):
	model = Inventario
	form_class = InventarioForm
	template_name = 'inventario/inventario_form.html'
	success_url = reverse_lazy('inventarioproducto:inventariop_crear')

class InventarioUpdate(UpdateView):
	model = Inventario
	form_class = InventarioForm
	template_name = 'inventario/inventario_form.html'
	success_url = reverse_lazy('plato_listar')

class InventarioDelete(DeleteView):
	model = Inventario
	form_class = InventarioForm
	template_name = 'inventario/inventario_delete.html'
	success_url = reverse_lazy('plato_listar')

templates/inventario/index.html
{% extends 'base/base.html' %}

{% block content %}
<h1>{{ titulo }}</h1>
{% if form %}
<form method="POST" action="">
	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit">Registrar venta</button>
</form>
{% endif %}
{% endblock %}

templates/inventario/inventario_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.id }},{{ object.descripcion }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'inventario:inventario_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/inventario/inventario_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="POST" >
	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit">Registrar</button>
</form>

{% endblock %}

templates/inventario/inventario_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>fecha</td>
			<td>descripcion</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		
		{% for inventario in object_list %}
		
        <tr>
			<td>{{ inventario.id }}</td>
			<td>{{ inventario.fecha}}</td>
			<td>{{ inventario.descripcion }}</td>
			
			<td>
				<a class="btn btn-primary" href="{% url 'inventario:inventario_editar' inventario.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'inventario:inventario_eliminar' inventario.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% else %}
		<h1>No hay registros de inventarios </h1>
		{% endif %}
	</tbody>
</table> 

{% endblock%}